apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # deploys first
  labels:
    name: ecommerce
    environment: production
    istio-injection: enabled # Enable Istio sidecar injection
